FlottTown_House1_MapScripts::
	.byte 0


FlottTown_House1_Dad::
# 5 "data/maps/FlottTown_House1/scripts.pory"
	msgbox FlottTown_House1_Text_FlottTownsQuiet, MSGBOX_NPC
# 6 "data/maps/FlottTown_House1/scripts.pory"
	waitmessage
# 7 "data/maps/FlottTown_House1/scripts.pory"
	closemessage
	end


FlottTown_House1_Mom::
# 12 "data/maps/FlottTown_House1/scripts.pory"
	msgbox FlottTown_House1_Text_ItsPeacefulOutHere, MSGBOX_NPC
# 13 "data/maps/FlottTown_House1/scripts.pory"
	waitmessage
# 14 "data/maps/FlottTown_House1/scripts.pory"
	closemessage
	end


FlottTown_House1_Doll::
# 19 "data/maps/FlottTown_House1/scripts.pory"
	msgbox FlottTown_House1_Text_CrushYou, MSGBOX_NPC
# 20 "data/maps/FlottTown_House1/scripts.pory"
	waitmessage
# 21 "data/maps/FlottTown_House1/scripts.pory"
	closemessage
	end


FlottTown_House1_Text_CrushYou::
# 25 "data/maps/FlottTown_House1/scripts.pory"
	.string "It's an enormous Snorlax doll. You fear\n"
	.string "that it may somehow crush you with it's\l"
	.string "immense size.$"

FlottTown_House1_Text_FlottTownsQuiet::
# 29 "data/maps/FlottTown_House1/scripts.pory"
	.string "Oh, you must be one of the new girls\n"
	.string "that just moved in! I hope you like it\l"
	.string "here. It's really quiet and peaceful.$"

FlottTown_House1_Text_ItsPeacefulOutHere::
# 33 "data/maps/FlottTown_House1/scripts.pory"
	.string "Hello! It's nice to meet you! You're one\n"
	.string "of the new girls that just moved in,\l"
	.string "right? You're going to have a wonderful\l"
	.string "time here in Flott Town.\n"
	.string "Our family moved from the big city, and\l"
	.string "it's been a wonderful change of pace.$"
