gText_Diancie_CanYouHearMe::
	.string "…\p"
	.string "Hello? Can you hear me?\p"
	.string "…\p"
	.string "Oh! A presence! I knew this would work!\l"
	.string "Tell me…\p"
	.string "$"

gText_Diancie_ChooseApperance::
	.string "What do you look like?"
	.string "$"


gText_Diancie_Resonate::
	.string "Can you tell me more about yourself?\n"
	.string "What do you resonate with the most?\p"
	.string "$"

gText_Birch_WhatAUniqueAura::
	.string "Wow… what a unique aura you have. What\n"
	.string "about your name?"
	.string "$"

gText_Birch_SoItsPlayer::
	.string "Is it {PLAYER}{KUN}?\p"
	.string "$"

gText_Diancie_CanIMeetYou::
	.string "I see… What a beautiful name! Can we\n"
	.string "meet, {PLAYER}? I'd love to know more…\p"
	.string "$"

gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Intro_AndYourName::
	.string "Input your name.$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
