# 1 "data/scripts/movement.pory"

# 2 "data/scripts/movement.pory"
@ Starting from here, these movements are considered
# 3 "data/scripts/movement.pory"
@ 'safe' (won't put follower into a Pokeball)
# 4 "data/scripts/movement.pory"
Common_Movement_FollowerSafeStart::

# 6 "data/scripts/movement.pory"
Common_Movement_QuestionMark:
# 7 "data/scripts/movement.pory"
	emote_question_mark
# 8 "data/scripts/movement.pory"
	step_end

# 11 "data/scripts/movement.pory"
Common_Movement_ExclamationMark:
# 12 "data/scripts/movement.pory"
	emote_exclamation_mark
# 13 "data/scripts/movement.pory"
	step_end

# 16 "data/scripts/movement.pory"
Common_Movement_Delay48:
# 17 "data/scripts/movement.pory"
	delay_16
# 18 "data/scripts/movement.pory"
	delay_16
# 19 "data/scripts/movement.pory"
	delay_16
# 20 "data/scripts/movement.pory"
	step_end

# 22 "data/scripts/movement.pory"
Common_Movement_FacePlayer:
# 23 "data/scripts/movement.pory"
	face_player
# 24 "data/scripts/movement.pory"
	step_end

# 26 "data/scripts/movement.pory"
Common_Movement_FaceAwayPlayer:
# 27 "data/scripts/movement.pory"
	face_away_player
# 28 "data/scripts/movement.pory"
	step_end

# 30 "data/scripts/movement.pory"
Common_Movement_FaceOriginalDirection:
# 31 "data/scripts/movement.pory"
	face_original_direction
# 32 "data/scripts/movement.pory"
	step_end

# 34 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFasterLeft:
# 35 "data/scripts/movement.pory"
	walk_in_place_faster_left
# 36 "data/scripts/movement.pory"
	step_end

# 38 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFasterUp:
# 39 "data/scripts/movement.pory"
	walk_in_place_faster_up
# 40 "data/scripts/movement.pory"
	step_end

# 42 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFasterRight:
# 43 "data/scripts/movement.pory"
	walk_in_place_faster_right
# 44 "data/scripts/movement.pory"
	step_end

# 46 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFasterDown:
# 47 "data/scripts/movement.pory"
	walk_in_place_faster_down
# 48 "data/scripts/movement.pory"
	step_end

# 50 "data/scripts/movement.pory"
Common_Movement_FaceRight:
# 51 "data/scripts/movement.pory"
	face_right
# 52 "data/scripts/movement.pory"
	step_end

# 54 "data/scripts/movement.pory"
Common_Movement_FaceLeft:
# 55 "data/scripts/movement.pory"
	face_left
# 56 "data/scripts/movement.pory"
	step_end

# 58 "data/scripts/movement.pory"
Common_Movement_FaceDown:
# 59 "data/scripts/movement.pory"
	face_down
# 60 "data/scripts/movement.pory"
	step_end

# 62 "data/scripts/movement.pory"
Common_Movement_FaceUp:
# 63 "data/scripts/movement.pory"
	face_up
# 64 "data/scripts/movement.pory"
	step_end

# 66 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceDown:
# 67 "data/scripts/movement.pory"
	walk_in_place_down
# 68 "data/scripts/movement.pory"
	step_end

# 70 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceLeft:
# 71 "data/scripts/movement.pory"
	walk_in_place_left
# 72 "data/scripts/movement.pory"
	step_end

# 74 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceRight:
# 75 "data/scripts/movement.pory"
	walk_in_place_right
# 76 "data/scripts/movement.pory"
	step_end

# 79 "data/scripts/movement.pory"

# 80 "data/scripts/movement.pory"
// End of follower-safe movements
# 81 "data/scripts/movement.pory"
Common_Movement_FollowerSafeEnd::
# 82 "data/scripts/movement.pory"
	step_end

# 84 "data/scripts/movement.pory"
Common_Movement_WalkUp6:
# 85 "data/scripts/movement.pory"
	walk_up
# 86 "data/scripts/movement.pory"
	walk_up
# 87 "data/scripts/movement.pory"
	walk_up
# 88 "data/scripts/movement.pory"
	walk_up
# 89 "data/scripts/movement.pory"
	walk_up
# 90 "data/scripts/movement.pory"
	walk_up
# 91 "data/scripts/movement.pory"
	step_end

# 93 "data/scripts/movement.pory"
Common_Movement_WalkUp4:
# 94 "data/scripts/movement.pory"
	walk_up
# 95 "data/scripts/movement.pory"
	walk_up
# 96 "data/scripts/movement.pory"
	walk_up
# 97 "data/scripts/movement.pory"
	walk_up
# 98 "data/scripts/movement.pory"
	step_end

# 100 "data/scripts/movement.pory"
Common_Movement_Delay32:
# 101 "data/scripts/movement.pory"
	delay_16
# 102 "data/scripts/movement.pory"
	delay_16
# 103 "data/scripts/movement.pory"
	step_end

# 105 "data/scripts/movement.pory"
Common_Movement_WalkUp:
# 106 "data/scripts/movement.pory"
	walk_up
# 107 "data/scripts/movement.pory"
	step_end

# 109 "data/scripts/movement.pory"
Common_Movement_WalkRight:
# 110 "data/scripts/movement.pory"
	walk_right
# 111 "data/scripts/movement.pory"
	step_end

# 113 "data/scripts/movement.pory"
Common_Movement_WalkLeft:
# 114 "data/scripts/movement.pory"
	walk_left
# 115 "data/scripts/movement.pory"
	step_end

# 118 "data/scripts/movement.pory"
Common_Movement_WalkUp2:
# 119 "data/scripts/movement.pory"
	walk_up
# 120 "data/scripts/movement.pory"
	walk_up
# 121 "data/scripts/movement.pory"
	step_end
